= Authenticating with Google

TIP: If you set up an SSAT login account with username and password, go to xref:authenticating-with-username.adoc[Login] instructions

Jump to the instructions for the service you want to access:

* xref:#_the_exchange[The Exchange]
* xref:#_discussion_forums[Discussion Forums]
* xref:#_ssat_mylearning[SSAT MyLearning]
* xref:#_ssat_myportfolio[SSAT MyPortfolio]


== The Exchange

include::partial$partial-login-exchange.adoc[]

include::partial$partial-login-google.adoc[]

NOTE: It can take 10-15 seconds after your first login for your account to be granted access to any restricted areas of the site that you should have access to , please refresh your browser after that time to see them.

== Discussion Forums

include::partial$partial-login-discourse.adoc[]

include::partial$partial-login-google.adoc[]

NOTE: It can take 10-15 seconds after your first login for your account to be granted access to any restricted discussion categories, please refresh your browser after that time to see them.

== SSAT MyLearning

include::partial$partial-login-mylearning.adoc[]

include::partial$partial-login-google.adoc[]

NOTE: We normally pre-add delegates to course so on your first access you should be able to see the course you are signed up for in the Dashboard. If we haven't pre-enroled you then it can take 10-15 seconds after your first login for your account to be granted access, please refresh your browser after that time to get access.

== SSAT MyPortfolio

include::partial$partial-login-myportfolio.adoc[]

include::partial$partial-login-google.adoc[]





