= Authenticating with Username and Password

IMPORTANT: If you are looking for guidance about the xref:lpa24public:ROOT:index.adoc[Lead Practitioner Accreditation system (January 2025 onwards)] please navigate to the xref:lpa24public:ROOT:index.adoc[documentation for that system].

TIP: If you are using Google login, go to xref:authenticating-with-google.adoc[One-step login with Google]

Jump to the instructions for the service you want to access:

* xref:#_the_library[The Library]
* xref:#_ssat_mylearning[SSAT MyLearning]


include::partial$partial-forgotten-details.adoc[]


== The Library

include::partial$partial-login-ssatmainsite.adoc[]

include::partial$partial-login-up.adoc[]

NOTE: It can take 10-15 seconds after your first login for your account to be granted access to any restricted areas of the site that you should have access to , please refresh your browser after that time to see them.

////
== Discussion Forums

include::partial$partial-login-discourse.adoc[]

include::partial$partial-login-up.adoc[]

NOTE: It can take 10-15 seconds after your first login for your account to be granted access to any restricted discussion categories, please refresh your browser after that time to see them.
////

== SSAT MyLearning

include::partial$partial-login-mylearning.adoc[]

include::partial$partial-login-up.adoc[]

NOTE: We normally pre-add delegates to course so on your first access you should be able to see the course you are signed up for in the Dashboard. If we haven't pre-enroled you then it can take 10-15 seconds after your first login for your account to be granted access, please refresh your browser after that time to get access.

////
== SSAT MyPortfolio

include::partial$partial-login-myportfolio.adoc[]

include::partial$partial-login-up.adoc[]
////